---
- hosts: new_odroid
  vars_files:
    - odroid_config.yml
  vars: 
    ansible_facts_mac_address: '{{ ansible_facts["eth0"]["macaddress"] }}'

  tasks:
    - debug: var=ansible_facts_mac_address
    - debug: var=ansible_facts.hostname
    
    - name: Run fstrim /
      shell: fstrim -v /

    - name: Enable fstrim once a week
      systemd:
        name: fstrim.timer
        enabled: yes


