# ansible-playbook -i hosts 00-fstrim.yaml --extra-vars="hosts=xxx"
---
- hosts: '{{ hosts }}'
  vars: 
    ansible_facts_mac_address: '{{ ansible_facts["eth0"]["macaddress"] }}'

  tasks:
    - debug: var=ansible_facts_mac_address
    - debug: var=ansible_facts.hostname
    
    - name: Run fstrim /
      become: yes
      shell: fstrim -v /

    - name: Enable fstrim once a week
      become: yes
      systemd:
        name: fstrim.timer
        enabled: yes


