---
- hosts: new_odroid
  vars_files:
    - odroid_config.yml
  vars: 
    ansible_facts_mac_address: '{{ ansible_facts["eth0"]["macaddress"] }}'

  tasks:
    - debug: var=ansible_facts_mac_address
    - debug: var=ansible_facts.hostname
    - name: Set timezone to Bucharest
      timezone:
        name: Europe/Bucharest
    - name: Run locale-gen en_US.UTF-8
      shell: locale-gen en_US.UTF-8


