---
- hosts: new_odroid
  vars_files:
    - odroid_config.yml
  vars: 
    ansible_facts_mac_address: '{{ ansible_facts["eth0"]["macaddress"] }}'

  tasks:
    - debug: var=ansible_facts_mac_address
    - debug: var=ansible_facts.hostname
    - name: Ensure group "adrianp" exists
      become: yes
      group:
        name: adrianp
        state: present

    - name: Add group bluetooth
      become: yes
      group:
        name: bluetooth
        state: present
    
    - name: Add group pulse
      become: yes
      group:
        name: pulse
        state: present
    
    - name: Add group pulse-access
      become: yes
      group:
        name: pulse-access
        state: present

    - name: Add group lightdm
      become: yes
      group:
        name: lightdm
        state: present

    - name: Add group nopasswdlogin
      become: yes
      group:
        name: nopasswdlogin
        state: present

    - name: Add group dip
      become: yes
      group:
        name: dip
        state: present

    - name: Add group dialout
      become: yes
      group:
        name: dialout
        state: present

    - name: Add group sudo
      become: yes
      group:
        name: sudo
        state: present

    - name: Add group cdrom
      become: yes
      group:
        name: cdrom
        state: present

    - name: Add the user 'adrianp' with a bash shell, appending groups
      become: yes
      user:
        name: adrianp
        shell: /bin/bash
        create_home: yes
        generate_ssh_key: yes
        group: adrianp
        uid: 1001
        password: '{{ new_odroid["odroid"]["adrianp"] }}'
        groups: root,adm,disk,dialout,cdrom,sudo,audio,dip,video,bluetooth,lightdm,nopasswdlogin,pulse,pulse-access
        append: yes
    
    - name: Change root password
      become: yes
      user:
        name: root
        password: '{{ new_odroid["odroid"]["root"] }}'

    - name: Set up multiple authorized keys for adrianp
      become: yes
      authorized_key:
        user: adrianp
        state: present
        key: '{{ item }}'
      with_file:
        - /home/adrianp/.ssh/id_rsa.pub
        - /home/adrianp/.ssh/id_rsa_frost.pub
        - /home/adrianp/.ssh/id_rsa_2020.pub
    
    - name: Set up multiple authorized keys for root
      become: yes
      authorized_key:
        user: root
        state: present
        key: '{{ item }}'
      with_file:
        - /home/adrianp/.ssh/id_rsa.pub
        - /home/adrianp/.ssh/id_rsa_frost.pub
        - /home/adrianp/.ssh/id_rsa_2020.pub

    
