---
- hosts: new_odroid
  vars_files:
    - odroid_config.yml
  vars: 
    ansible_facts_mac_address: '{{ ansible_facts["eth0"]["macaddress"] }}'

  tasks:
    - debug: var=new_odroid["odroid"]["hostname"]
    - debug: var=ansible_facts.hostname
    - hostname:
        name: '{{ new_odroid["odroid"]["hostname"] }}'

    - name: Update /etc/hosts
      blockinfile:
          path: /etc/hosts
          create: yes
          block: |
            127.0.0.1 localhost {{ new_odroid["odroid"]["hostname"] }}

            # The following lines are desirable for IPv6 capable hosts
            ::1 ip6-localhost ip6-loopback
            fe00::0 ip6-localnet
            ff00::0 ip6-mcastprefix
            ff02::1 ip6-allnodes
            ff02::2 ip6-allrouters
            ff02::3 ip6-allhosts
        