# ansible-playbook -i hosts 04-ondemand-governor.yaml --extra-vars="hosts=xxx"
---
- hosts: '{{ hosts }}'
  vars: 
    ansible_facts_mac_address: '{{ ansible_facts["eth0"]["macaddress"] }}'

  tasks:

    - debug: var=ansible_facts.hostname
    - name: Create the file, if it doesnt exist already
      become: yes
      file:
          path: /etc/default/cpufrequtils
          state: touch

    - name: Set governor to ondemand
      become: yes
      lineinfile:
        path: /etc/default/cpufrequtils
        regexp: '^GOVERNOR=.*$'
        line: 'GOVERNOR="ondemand"'
        backrefs: yes

    - name: Restart cpufrequtils
      become: yes
      systemd:
        state: restarted
        daemon_reload: yes
        name: cpufrequtils
