# ansible-playbook -i hosts 13-install-xfce.yaml --extra-vars="hosts=xxx"
- hosts: '{{ hosts }}'
  tasks:
  - name: Install xfce packages
    become: yes
    apt: 
      name: 
        - xfce4
        - dmz-cursor-theme
        - elementary-xfce-icon-theme
        - fonts-noto-core
        - fonts-noto-hinted
        - fonts-noto-ui-core
        - greybird-gtk-theme
        - xfce4-appfinder
        - xfce4-notifyd
        - xfce4-panel
        - xfce4-session
        - xfce4-settings
        - xfconf
        - xfdesktop4
        - xfdesktop4-data
        - xfwm4
        - xubuntu-artwork
        - xubuntu-core
        - xubuntu-default-settings
        - xubuntu-wallpapers
        # recommended packages
        - thunar-archive-plugin
        - thunar-media-tags-plugin
        - xcursor-themes
        - xfce4-cpugraph-plugin
        - xfce4-dict
        - xfce4-mailwatch-plugin
        - xfce4-netload-plugin
        - xfce4-notes-plugin
        - xfce4-places-plugin
        - xfce4-systemload-plugin
        - xfce4-taskmanager
        - xfce4-verve-plugin
        - xfce4-weather-plugin
        - xfce4-xkb-plugin
        - xfpanel-switch
        - numlockx 
        - pavucontrol
        - xfce4-indicator-plugin 
        - xfce4-power-manager 
        - xfce4-pulseaudio-plugin
        - xfce4-screensaver 
        - xfce4-screenshooter 
        - xfce4-statusnotifier-plugin
        - xfce4-terminal 
        - xfce4-whiskermenu-plugin 
        - mousepad
        - pastebinit
        - nautilus
        - xfce4-goodies
      install_recommends: no
  - name: Ensure /home/adrianp/.local/ exists
    ansible.builtin.file:
      path: /home/adrianp/.local
      state: directory
      mode: '0755'
  - name: Ensure /home/adrianp/.local/share/ exists
    ansible.builtin.file:
      path: /home/adrianp/.local/share/
      state: directory
      mode: '0755'
  - name: /home/adrianp/.local/share/xfce4-panel-profiles/ exists
    ansible.builtin.file:
      path: /home/adrianp/.local/share/xfce4-panel-profiles/
      state: directory
      mode: '0755'
  - name: Copy panel1screen.tar.bz2 to /home/adrianp/.local/share/xfce4-panel-profiles/
    copy:
      src: files/panel1screen.tar.bz2
      dest: /home/adrianp/.local/share/xfce4-panel-profiles/
      owner: adrianp
      group: adrianp
      mode: '0644'
  - name: Copy panel2screens.tar.bz2 to /home/adrianp/.local/share/xfce4-panel-profiles/
    copy:
      src: files/panel2screens.tar.bz2
      dest: /home/adrianp/.local/share/xfce4-panel-profiles/
      owner: adrianp
      group: adrianp
      mode: '0644'

