# ansible-playbook -i hosts 14-install-gui.yaml --extra-vars="hosts=xxx"
- hosts: '{{ hosts }}'
  tasks:
  - name: Install GUI tools
    become: yes
    apt: 
      name: 
        - keepass2
        - keepassxc
        - xpra
        - firefox
        - openvpn
  - name: Download gpg key for vscodium
    become: yes
    shell: >
      wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor |sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg
  - name: Add vscodium repo
    become: yes
    shell: >
      echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://download.vscodium.com/debs vscodium main' | sudo tee /etc/apt/sources.list.d/vscodium.list
  - name: Update package cache
    become: yes
    apt:
      update_cache: yes
  - name: Install vscodium
    become: yes
    apt:
      name:
        - codium

    
