# ansible-playbook -i hosts 17-xfce-customizations.yaml --extra-vars="hosts=xxx"
- hosts: '{{ hosts }}'
  become: yes
  vars:
    conf_dir: "/home/adrianp/.config/xfce4"
    username: "adrianp"
    group: "adrianp"
  tasks:
  - name: "Ensure {{conf_dir}} exists"
    file:
      path: "{{conf_dir}}"
      state: directory
      owner: "{{username}}"
      group: "{{group}}"
  
  - name: "Ensure {{conf_dir}}/terminal exists"
    file:
      path: "{{conf_dir}}/terminal"
      state: directory
      owner: "{{username}}"
      group: "{{group}}"
  
  - name: "Copy local terminalrc"
    copy:
      src: "{{conf_dir}}/terminal/terminalrc"
      dest: "{{conf_dir}}/terminal/terminalrc"
      owner: "{{username}}"
      group: "{{group}}"
  
  - name: "Ensure {{conf_dir}}/xfconf/xfce-perchannel-xml/ exists"
    file:
      path: "{{conf_dir}}/xfconf/xfce-perchannel-xml"
      state: directory
      owner: "{{username}}"
      group: "{{group}}"
  - name: "Copy local keyboard-layout.xml"
    copy:
      src: "{{conf_dir}}/xfconf/xfce-perchannel-xml/keyboard-layout.xml"
      dest: "{{conf_dir}}/xfconf/xfce-perchannel-xml/keyboard-layout.xml"
      owner: "{{username}}"
      group: "{{group}}"
  - name: "Copy local keyboards.xml"
    copy:
      src: "{{conf_dir}}/xfconf/xfce-perchannel-xml/keyboards.xml"
      dest: "{{conf_dir}}/xfconf/xfce-perchannel-xml/keyboards.xml"
      owner: "{{username}}"
      group: "{{group}}"
  - name: "Copy local xfce4-keyboard-shortcuts.xml"
    copy:
      src: "{{conf_dir}}/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
      dest: "{{conf_dir}}/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
      owner: "{{username}}"
      group: "{{group}}"
  - name: "Copy local xfce4-notifyd.xml"
    copy:
      src: "{{conf_dir}}/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml"
      dest: "{{conf_dir}}/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml"
      owner: "{{username}}"
      group: "{{group}}"
  - name: "Tar local cursors (~/.icons) before transfer"
    archive:
      path: "/home/adrianp/.icons"
      dest: "/tmp/adrianp-icons.tgz"
    delegate_to: "localhost"

  - name: "Transfer /tmp/adrianp-icons.tgz"
    copy:
      src: "/tmp/adrianp-icons.tgz"
      dest: "/home/adrianp/"
      owner: "{{username}}"
      group: "{{group}}"

  - name: "Ensure .icons exists"
    file:
      path: "/home/{{username}}/.icons"
      state: directory
      owner: "{{username}}"
      group: "{{group}}"

  - name: "Unarchive /home/adrianp/adrianp-icons.tgz"
    unarchive:
      src: "/home/adrianp/adrianp-icons.tgz"
      dest: "/home/adrianp"
      remote_src: yes

  - name: "Tar local themes (~/.themes) before transfer"
    archive:
      path: "/home/adrianp/.themes"
      dest: "/tmp/adrianp-themes.tgz"
    delegate_to: "localhost"

  - name: "Transfer /tmp/adrianp-themes.tgz"
    copy:
      src: "/tmp/adrianp-themes.tgz"
      dest: "/home/adrianp/"
      owner: "{{username}}"
      group: "{{group}}"

  - name: "Ensure .themes exists"
    file:
      path: "/home/{{username}}/.themes"
      state: directory
      owner: "{{username}}"
      group: "{{group}}"

  - name: "Unarchive /home/adrianp/adrianp-themes.tgz"
    unarchive:
      src: "/home/adrianp/adrianp-themes.tgz"
      dest: "/home/adrianp"
      remote_src: yes

  
  

  
